apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: rabbit
spec:
  ports:
  - port: 15672
    name: admin
    protocol: TCP
    targetPort: 15672
  - port: 5672
    name: broker
    protocol: TCP
    targetPort: 5672
  selector:
    run: rabbit
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: rabbit
  name: rabbit
spec:
  containers:
  - image: rabbitmq:management
    name: rabbit
    ports:
    - containerPort: 15672
    - containerPort: 5672
    # resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
